-- Existing internal template catalog only. Never overwrite edited live records.
begin;
insert into public.templates (name,slug,industry,style,short_description,thumbnail_url,demo_url,screenshots,pages,features,starting_price,mobile_responsive,featured,status,created_at) values
('Studio Launch','studio-launch','Agency','Expressive','A confident agency website for presenting expertise, selected work and a clear project enquiry path.','/template-previews/studio-launch','/templates/studio-launch/demo',ARRAY['/template-previews/studio-launch?view=home','/template-previews/studio-launch?view=inner']::text[],ARRAY['Home','Work','Services','About','Contact']::text[],ARRAY['Project-led homepage','Portfolio grid','Service overview','Enquiry call to action']::text[],399,true,true,'published','2026-08-20T09:00:00.000Z'),
('Local Pro','local-pro','Local Business','Clean','A clear service website designed to turn local searches into qualified enquiries.','/template-previews/local-pro','/templates/local-pro/demo',ARRAY['/template-previews/local-pro?view=home','/template-previews/local-pro?view=inner']::text[],ARRAY['Home','Services','Service Detail','About','Contact']::text[],ARRAY['Service highlights','Local trust section','Contact form','Mobile-first calls to action']::text[],399,true,true,'published','2026-08-18T09:00:00.000Z'),
('Ironline Build','ironline-build','Construction','Bold','A direct construction website for showcasing capabilities, completed work and quote-ready services.','/template-previews/ironline-build','/templates/ironline-build/demo',ARRAY['/template-previews/ironline-build?view=home','/template-previews/ironline-build?view=inner']::text[],ARRAY['Home','Services','Projects','About','Contact']::text[],ARRAY['Capability overview','Project gallery','Service detail layouts','Quote enquiry flow']::text[],399,true,true,'published','2026-08-15T09:00:00.000Z'),
('Consult Flow','consult-flow','Consulting','Editorial','An authority-led website for consultants who need to explain value and capture leads.','/template-previews/consult-flow','/templates/consult-flow/demo',ARRAY['/template-previews/consult-flow?view=home','/template-previews/consult-flow?view=inner']::text[],ARRAY['Home','Expertise','Insights','About','Contact']::text[],ARRAY['Expertise pages','Insight previews','Consultation call to action','Lead form']::text[],399,true,true,'published','2026-08-12T09:00:00.000Z'),
('ClearNest Cleaning','clearnest-cleaning','Cleaning','Clean','A fresh service website that makes cleaning packages, coverage areas and quote requests easy to understand.','/template-previews/clearnest-cleaning','/templates/clearnest-cleaning/demo',ARRAY['/template-previews/clearnest-cleaning?view=home','/template-previews/clearnest-cleaning?view=inner']::text[],ARRAY['Home','Services','Service Areas','About','Contact']::text[],ARRAY['Service package cards','Coverage area section','Before-and-after layout','Quote request flow']::text[],399,true,true,'published','2026-08-09T09:00:00.000Z'),
('Keyframe Property','keyframe-property','Real Estate','Premium','A polished property showcase for independent agencies and specialist developments.','/template-previews/keyframe-property','/templates/keyframe-property/demo',ARRAY['/template-previews/keyframe-property?view=home','/template-previews/keyframe-property?view=inner']::text[],ARRAY['Home','Properties','Property Detail','Services','About','Contact']::text[],ARRAY['Property cards','Listing detail layout','Agent enquiry flow','Location highlights']::text[],899,true,true,'published','2026-08-05T09:00:00.000Z'),
('Table & Tide','table-and-tide','Restaurant','Editorial','A warm restaurant concept built around menu discovery and reservation intent.','/template-previews/table-and-tide','/templates/table-and-tide/demo',ARRAY['/template-previews/table-and-tide?view=home','/template-previews/table-and-tide?view=inner']::text[],ARRAY['Home','Menu','Story','Reservations']::text[],ARRAY['Menu presentation','Opening hours','Location section','Reservation call to action']::text[],399,true,false,'published','2026-08-01T09:00:00.000Z'),
('Brightline Dental','brightline-dental','Dental','Calm','A calm dental practice concept planned around treatments, patient information and appointment enquiries.','/template-previews/brightline-dental',null,ARRAY[]::text[],ARRAY['Home','Treatments','Dentists','Patient Info','About','Contact']::text[],ARRAY['Treatment directory','Dentist profiles','Patient information','Appointment call to action']::text[],null,true,false,'coming_soon','2026-07-28T09:00:00.000Z'),
('Groundwork Pro','groundwork-pro','Construction','Clean','A structured contractor concept planned for services, accreditations, project coverage and enquiries.','/template-previews/groundwork-pro',null,ARRAY[]::text[],ARRAY['Home','Services','Projects','Safety','About','Contact']::text[],ARRAY['Service area overview','Project case-study layout','Safety and compliance section','Enquiry form']::text[],null,true,false,'coming_soon','2026-07-24T09:00:00.000Z'),
('Saffron House','saffron-house','Restaurant','Warm','A welcoming restaurant concept planned around signature dishes, atmosphere and reservation intent.','/template-previews/saffron-house',null,ARRAY[]::text[],ARRAY['Home','Menu','Gallery','Our Story','Reservations']::text[],ARRAY['Signature menu sections','Dining gallery','Opening hours','Reservation call to action']::text[],null,true,false,'coming_soon','2026-07-20T09:00:00.000Z')
on conflict (slug) do nothing;
commit;
