"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Download, FileDown, Mail, Search } from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

type RequestItem = { product_name: string; category_name: string; quantity: string; unit: string; condition: string; specification: string };
type CustomerRequest = { id: string; reference_number: string; full_name: string; company_name: string; email: string; whatsapp: string; country: string; request_purpose: string; destination_country: string; destination_port: string; status: string; assigned_to_name: string; admin_notes: string; attachment_url?: string; created_at: string; customer_request_items: RequestItem[] };
const statuses = ["New", "Under Review", "Discussion Started", "Sourcing Suppliers", "Quotation Sent", "Negotiation", "Deal Confirmed", "Closed", "Cancelled"];
const demo: CustomerRequest[] = [
  { id:"demo-1", reference_number:"TBG-20260719-A4D912", full_name:"Daniel Mensah", company_name:"Akwaaba Industrial Supply", email:"daniel@example.com", whatsapp:"+233 20 000 0000", country:"Ghana", request_purpose:"I need a quotation", destination_country:"Ghana", destination_port:"Tema", status:"New", assigned_to_name:"Unassigned", admin_notes:"", created_at:"2026-07-19", attachment_url:"customer-requests/specification.pdf", customer_request_items:[{ product_name:"Electric forklifts", category_name:"Forklifts and Warehouse Equipment", quantity:"4", unit:"Units", condition:"Used", specification:"2.5 ton, 4.5 m mast, battery report required" },{ product_name:"PVC tarpaulin rolls", category_name:"Packaging Materials", quantity:"20000", unit:"Meters", condition:"New", specification:"650 GSM, blue, UV treated" }] },
  { id:"demo-2", reference_number:"TBG-20260718-77BC20", full_name:"Amina Hassan", company_name:"Rift Valley Processors", email:"amina@example.com", whatsapp:"+254 700 000000", country:"Kenya", request_purpose:"I need supplier sourcing", destination_country:"Kenya", destination_port:"Mombasa", status:"Under Review", assigned_to_name:"Mika Sato", admin_notes:"Confirm three-phase voltage.", created_at:"2026-07-18", customer_request_items:[{ product_name:"Food-processing machinery", category_name:"Industrial Machinery", quantity:"1", unit:"Sets", condition:"Any", specification:"Pulse cleaning and packing line, 2 t/hour" }] },
  { id:"demo-3", reference_number:"TBG-20260717-91E4AA", full_name:"Omar Rahman", company_name:"Gulf Circular Materials", email:"omar@example.com", whatsapp:"+971 50 000 0000", country:"United Arab Emirates", request_purpose:"I want to discuss", destination_country:"United Arab Emirates", destination_port:"Jebel Ali", status:"Discussion Started", assigned_to_name:"Priya Nair", admin_notes:"Buyer requests monthly programme.", created_at:"2026-07-17", customer_request_items:[{ product_name:"Recycled granules", category_name:"Plastics and Polymers", quantity:"100", unit:"Metric tons", condition:"Recycled", specification:"PP injection grade, black, MFI 10–15" },{ product_name:"Plastic additives", category_name:"Plastics and Polymers", quantity:"5", unit:"Metric tons", condition:"New", specification:"Impact modifier compatible with recycled PP" }] },
];

export function CustomerRequestManager() {
  const [rows, setRows] = useState(demo); const [query, setQuery] = useState(""); const [purpose, setPurpose] = useState(""); const [status, setStatus] = useState(""); const [expanded, setExpanded] = useState<string | null>(demo[0].id);
  useEffect(() => { const supabase = createClient(); if (!supabase) return; supabase.from("customer_requests").select("*, customer_request_items(*)").order("created_at", { ascending:false }).then(({ data, error }) => { if (data?.length) setRows(data as CustomerRequest[]); if (error) toast.error("Customer requests could not be refreshed.") }); }, []);
  const filtered = useMemo(() => rows.filter(row => (!query || `${row.full_name} ${row.company_name} ${row.country} ${row.reference_number}`.toLowerCase().includes(query.toLowerCase())) && (!purpose || row.request_purpose === purpose) && (!status || row.status === status)), [rows, query, purpose, status]);
  async function updateRow(id: string, changes: Partial<CustomerRequest>) { setRows(value => value.map(row => row.id === id ? { ...row, ...changes } : row)); const supabase = createClient(); if (supabase && !id.startsWith("demo-")) { const { error } = await supabase.from("customer_requests").update(changes).eq("id", id); if (error) { toast.error(error.message); return; } } toast.success("Request updated"); }
  async function downloadDocument(row: CustomerRequest) { if (!row.attachment_url) { toast.info("No document was uploaded."); return; } const supabase = createClient(); if (!supabase || row.id.startsWith("demo-")) { toast.info("Document download is available when Supabase storage is connected."); return; } const { data, error } = await supabase.storage.from("trade-documents").createSignedUrl(row.attachment_url, 60, { download:true }); if (error || !data?.signedUrl) { toast.error(error?.message || "Document could not be opened."); return; } window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }
  function exportCsv() { const lines = ["reference,customer,company,country,purpose,status,assigned,products", ...filtered.map(row => [row.reference_number,row.full_name,row.company_name,row.country,row.request_purpose,row.status,row.assigned_to_name,row.customer_request_items.map(item => `${item.product_name} (${item.quantity} ${item.unit})`).join("; ")].map(value => `"${String(value).replace(/"/g, '""')}"`).join(","))]; const url = URL.createObjectURL(new Blob([lines.join("\n")], { type:"text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "customer-product-requests.csv"; anchor.click(); URL.revokeObjectURL(url); toast.success("Customer requests exported"); }

  return <section className="mt-8 rounded-xl border border-slate-200 bg-white">
    <div className="flex flex-col gap-4 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between"><div><span className="text-xs font-extrabold uppercase tracking-wider text-blue-700">Lead management</span><h2 className="mt-1 text-xl font-extrabold text-[#071a33]">Customer Product Requests</h2></div><button onClick={exportCsv} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 px-4 text-sm font-bold"><Download size={16}/>Export requests to CSV</button></div>
    <div className="grid gap-3 border-b border-slate-100 bg-slate-50 p-4 lg:grid-cols-[1fr_250px_210px]"><label className="relative"><Search className="absolute left-3.5 top-3.5 text-slate-400" size={17}/><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search customer, company, country or reference" className="pl-10"/></label><Select value={purpose} onChange={event => setPurpose(event.target.value)} aria-label="Filter purpose"><option value="">All request purposes</option>{[...new Set(rows.map(row => row.request_purpose))].map(value => <option key={value}>{value}</option>)}</Select><Select value={status} onChange={event => setStatus(event.target.value)} aria-label="Filter status"><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</Select></div>
    <div className="divide-y divide-slate-100">{filtered.map(row => <article key={row.id}><button onClick={() => setExpanded(expanded === row.id ? null : row.id)} className="grid w-full gap-3 p-5 text-left md:grid-cols-[150px_1.3fr_.7fr_.7fr_auto] md:items-center"><span className="font-mono text-xs font-bold text-blue-700">{row.reference_number}</span><span><strong className="block text-sm text-[#071a33]">{row.full_name}</strong><span className="text-xs text-slate-500">{row.company_name}</span></span><span className="text-sm text-slate-600">{row.country}</span><Badge className={row.status === "New" ? "bg-amber-50 text-amber-700" : ""}>{row.status}</Badge><ChevronDown size={17} className={`transition ${expanded === row.id ? "rotate-180" : ""}`}/></button>
      {expanded === row.id && <div className="border-t border-slate-100 bg-slate-50 p-5"><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div><h3 className="text-sm font-extrabold text-[#071a33]">Selected products ({row.customer_request_items.length})</h3><div className="mt-3 space-y-3">{row.customer_request_items.map((item,index) => <div key={`${item.product_name}-${index}`} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{item.product_name}</strong><span className="text-xs font-bold text-blue-700">{item.quantity} {item.unit} · {item.condition}</span></div><span className="mt-1 block text-xs text-slate-500">{item.category_name}</span>{item.specification && <p className="mt-2 text-xs leading-5 text-slate-600">{item.specification}</p>}</div>)}</div><div className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><p><b>Purpose:</b> {row.request_purpose}</p><p><b>Destination:</b> {row.destination_port}, {row.destination_country}</p><p><b>Email:</b> {row.email}</p><p><b>WhatsApp:</b> {row.whatsapp}</p></div></div><div className="space-y-4"><label className="block text-xs font-bold text-slate-600">Status<Select value={row.status} onChange={event => updateRow(row.id, { status:event.target.value })} className="mt-1">{statuses.map(value => <option key={value}>{value}</option>)}</Select></label><label className="block text-xs font-bold text-slate-600">Assigned team member<Select value={row.assigned_to_name || "Unassigned"} onChange={event => updateRow(row.id, { assigned_to_name:event.target.value })} className="mt-1"><option>Unassigned</option><option>Mika Sato</option><option>Priya Nair</option><option>Ahmed Khan</option><option>Trade Desk</option></Select></label><label className="block text-xs font-bold text-slate-600">Internal notes<Textarea value={row.admin_notes || ""} onChange={event => setRows(value => value.map(item => item.id === row.id ? { ...item, admin_notes:event.target.value } : item))} onBlur={() => updateRow(row.id, { admin_notes:row.admin_notes })} className="mt-1 min-h-24"/></label><div className="grid grid-cols-2 gap-2"><a href={`mailto:${row.email}?subject=${encodeURIComponent(`TradeBridge request ${row.reference_number}`)}`} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-blue-700 text-xs font-bold text-white"><Mail size={15}/>Contact buyer</a><button onClick={() => downloadDocument(row)} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white text-xs font-bold"><FileDown size={15}/>Document</button></div></div></div></div>}
    </article>)}</div>
    {!filtered.length && <div className="py-16 text-center text-sm text-slate-500">No customer requests match these filters.</div>}
  </section>;
}
