"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { CalendarDays, MapPin, Package, Search, ShieldCheck } from "lucide-react";
import { rfqs } from "@/lib/site-data";
import { formatDate } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
export function RfqMarketplace(){const[q,setQ]=useState("");const[category,setCategory]=useState("");const items=useMemo(()=>rfqs.filter(r=>(!q||`${r.product} ${r.specification} ${r.destination}`.toLowerCase().includes(q.toLowerCase()))&&(!category||r.category===category)),[q,category]);return <div className="container-site section-pad"><div className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-[1fr_260px]"><label className="relative"><Search className="absolute left-3.5 top-3.5 text-slate-400" size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} className="pl-10" placeholder="Search public buyer requirements"/></label><Select value={category} onChange={e=>setCategory(e.target.value)} aria-label="RFQ category"><option value="">All categories</option>{Array.from(new Set(rfqs.map(r=>r.category))).map(x=><option key={x}>{x}</option>)}</Select></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{items.map(r=><article key={r.product} className="rounded-xl border border-slate-200 bg-white p-6 transition hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-extrabold uppercase tracking-wider text-blue-700">{r.category}</span><h2 className="mt-2 text-xl font-extrabold text-[#071a33]">{r.product}</h2></div><Badge className={r.status==="Open"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}>{r.status}</Badge></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><span className="flex items-center gap-2 text-slate-600"><MapPin size={16} className="text-blue-700"/>Destination: <b>{r.destination}</b></span><span className="flex items-center gap-2 text-slate-600"><Package size={16} className="text-blue-700"/>Quantity: <b>{r.quantity}</b></span><span className="flex items-center gap-2 text-slate-600"><CalendarDays size={16} className="text-blue-700"/>Purchase: <b>{r.purchaseDate}</b></span><span className="text-xs text-slate-500 sm:text-right">Posted {formatDate(r.posted)}</span></div><div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-700"><strong>Specification:</strong> {r.specification}</div><div className="mt-5 flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={15}/>Buyer identity protected</span><Link href={`/auth/login?next=/supplier-dashboard`} className="inline-flex h-10 items-center rounded-lg bg-blue-700 px-4 text-sm font-bold text-white">Submit Offer</Link></div></article>)}</div>{!items.length&&<div className="py-20 text-center text-slate-500">No approved RFQs match those filters.</div>}</div>}
