"use client";
import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { products, categories } from "@/lib/site-data";
import { ProductCard } from "./product-card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";

export function ProductFilters({ initialCategory = "" }: { initialCategory?: string }) {
  const [query,setQuery] = useState(""); const [category,setCategory] = useState(initialCategory); const [origin,setOrigin] = useState(""); const [condition,setCondition] = useState(""); const [page,setPage] = useState(1); const perPage=6;
  const filtered = useMemo(() => products.filter(p => (!query || `${p.name} ${p.spec} ${p.category}`.toLowerCase().includes(query.toLowerCase())) && (!category || p.category === category) && (!origin || p.origin === origin) && (!condition || p.condition === condition)),[query,category,origin,condition]);
  const pages=Math.max(1,Math.ceil(filtered.length/perPage)); const shown=filtered.slice((page-1)*perPage,page*perPage);
  function reset(){setQuery("");setCategory("");setOrigin("");setCondition("");setPage(1)}
  return <div className="container-site section-pad"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4 md:p-5"><div className="grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_1fr_auto]"><label className="relative"><span className="sr-only">Search products</span><Search className="absolute left-3.5 top-3.5 text-slate-400" size={17}/><Input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search by product or specification" className="pl-10"/></label><Select aria-label="Filter by category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All categories</option>{categories.map(c=><option key={c.slug}>{c.name}</option>)}</Select><Select aria-label="Filter by origin" value={origin} onChange={e=>{setOrigin(e.target.value);setPage(1)}}><option value="">All origins</option><option>Japan</option><option>India</option></Select><Select aria-label="Filter by condition" value={condition} onChange={e=>{setCondition(e.target.value);setPage(1)}}><option value="">New & used</option><option>New</option><option>Used</option></Select><button onClick={reset} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700"><X size={16}/>Reset</button></div></div><div className="mt-8 flex items-center justify-between"><p className="text-sm text-slate-600"><strong className="text-[#071a33]">{filtered.length}</strong> sourcing options</p><span className="flex items-center gap-2 text-xs font-bold text-slate-500"><SlidersHorizontal size={15}/>Approved products only</span></div>{shown.length ? <div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{shown.map(p=><ProductCard key={p.slug} product={p}/>)}</div> : <div className="mt-8 rounded-xl border border-dashed border-slate-300 px-6 py-20 text-center"><PackageIcon/><h2 className="mt-4 text-xl font-bold text-[#071a33]">No matching products</h2><p className="mt-2 text-sm text-slate-500">Try clearing a filter or submit a custom sourcing request.</p><button onClick={reset} className="mt-5 text-sm font-bold text-blue-700">Clear all filters</button></div>} {pages>1 && <div className="mt-10 flex justify-center gap-2">{Array.from({length:pages},(_,i)=><button key={i} onClick={()=>setPage(i+1)} className={`size-10 rounded-lg text-sm font-bold ${page===i+1?"bg-blue-700 text-white":"border border-slate-300 bg-white"}`}>{i+1}</button>)}</div>}</div>;
}
function PackageIcon(){return <div className="mx-auto grid size-14 place-items-center rounded-full bg-slate-100 text-2xl">⌕</div>}
