import { websiteCaseStudy, leadIntakeCaseStudy, automationCaseStudy, aiCaseStudy } from "./case-studies";
import type { WorkProject } from "./types";

// These records describe TradeBridge Digital's own work and clearly labelled
// internal concepts. No client identities or unverified performance claims are used.
export const workProjects = [
  {
    name: "TradeBridge Digital Website System",
    slug: "tradebridge-digital-website-system",
    category: "Websites",
    project_type: "Internal Build",
    summary: "The modular website and content foundation being used for the TradeBridge Digital rebuild.",
    problem: "The existing sourcing website needs to become a focused digital-services platform without an unsafe one-time rewrite.",
    solution: "A phased Next.js rebuild with shared design foundations, reusable service content, a scalable template catalog and structured quote intake.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase-ready"],
    features: ["Reusable page sections", "Dynamic template catalog", "Validated quote form", "SEO and metadata foundations"],
    screenshots: ["/work-previews/tradebridge-digital-website-system"],
    demo_url: "/",
    github_url: null,
    case_study: websiteCaseStudy,
    status: "Internal Build",
  },
  {
    name: "Lead Intake Workspace",
    slug: "lead-intake-workspace",
    category: "Business Systems",
    project_type: "Concept Project",
    summary: "A concept for a focused workspace for receiving, qualifying and assigning new enquiries.",
    problem: "Small teams often manage leads across inboxes and spreadsheets, making ownership and follow-up difficult to see.",
    solution: "A single lead workspace concept with structured intake, pipeline stages, ownership and next-action visibility.",
    stack: ["Next.js", "TypeScript", "Supabase", "Zod"],
    features: ["Lead intake", "Pipeline stages", "Owner assignment", "Follow-up status"],
    screenshots: ["/work-previews/lead-intake-workspace"],
    demo_url: null,
    github_url: null,
    case_study: leadIntakeCaseStudy,
    status: "Concept Project",
  },
  {
    name: "Automation Operations Board",
    slug: "automation-operations-board",
    category: "Automation",
    project_type: "Concept Project",
    summary: "A concept for monitoring business workflows, handoffs, failures and tasks that need human attention.",
    problem: "Automated workflows become difficult to trust when teams cannot see failures, ownership or the last successful run.",
    solution: "A monitored operations-board concept that separates healthy workflows from exceptions requiring review.",
    stack: ["n8n", "Webhooks", "Supabase", "TypeScript"],
    features: ["Workflow health overview", "Exception queue", "Run history", "Human handoff states"],
    screenshots: ["/work-previews/automation-operations-board"],
    demo_url: null,
    github_url: null,
    case_study: automationCaseStudy,
    status: "Concept Project",
  },
  {
    name: "AI Lead Qualification Assistant",
    slug: "ai-lead-qualification-assistant",
    category: "AI Projects",
    project_type: "Concept Project",
    summary: "A controlled AI concept for reviewing enquiry context and preparing a structured qualification summary.",
    problem: "High enquiry volume can make initial review inconsistent, while fully automated decisions introduce unnecessary risk.",
    solution: "An assisted workflow concept that summarizes known information, applies agreed criteria and leaves approval with a person.",
    stack: ["OpenAI API", "Supabase", "n8n", "TypeScript"],
    features: ["Structured lead summary", "Qualification criteria", "Human approval point", "Audit-ready context"],
    screenshots: ["/work-previews/ai-lead-qualification-assistant"],
    demo_url: null,
    github_url: null,
    case_study: aiCaseStudy,
    status: "Concept Project",
  },
] as const satisfies readonly WorkProject[];
