import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, CheckCircle2, ClipboardCheck, ClipboardList, Earth, Handshake, ListChecks, MessageSquareText, PackageSearch, Scale, SearchCheck, Send, Ship } from "lucide-react";
import { opportunities } from "@/lib/site-data";
import { productCatalog } from "@/lib/product-catalog";
import { insightArticles } from "@/lib/insights-data";
import { SectionHeading } from "@/components/shared/section-heading";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = { title: "Global Sourcing Made Simple", description: "Connect with reliable suppliers from Japan, India and major sourcing markets through a transparent commission-based service." };

const trust = [[BadgeCheck, "Verified supplier network"], [Earth, "Multi-country sourcing"], [PackageSearch, "Buyer requirement matching"], [Scale, "Commission-based service"], [Handshake, "End-to-end deal coordination"]] as const;
const why = ["Japan-based sourcing access", "India supplier network", "International trade experience", "Product and supplier verification", "Fast quotation comparison", "Confidential buyer and supplier information", "Transparent commission-based service"];

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "Organization", name: "TradeBridge Global", url: process.env.NEXT_PUBLIC_SITE_URL || "https://tradebridge-global.example.com", description: "International sourcing and trade-matching company.", areaServed: ["Africa", "Asia", "Middle East"], knowsAbout: ["Industrial machinery", "International sourcing", "Trade matching"] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="relative min-h-[690px] overflow-hidden bg-[#071a33] text-white"><Image src="/port-logistics.jpg" alt="International shipping containers at a global logistics port" fill priority className="object-cover object-center" /><div className="absolute inset-0 hero-overlay" /><div className="absolute inset-0 grid-lines opacity-50"/><div className="container-site relative flex min-h-[690px] items-center py-20"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.14em] text-blue-100 backdrop-blur"><Earth size={15}/> Japan · India · Global markets</div><h1 className="display-title mt-7">Global Sourcing<br/><span className="text-blue-300">Made Simple</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200 md:text-xl">We connect international buyers with reliable suppliers from Japan, India, and other major sourcing markets.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/request" className="inline-flex h-13 items-center justify-center gap-2 rounded-lg bg-amber-400 px-6 text-sm font-extrabold text-slate-950 transition hover:bg-amber-300">Submit Your Requirement <ArrowRight size={17}/></Link><Link href="/products" className="inline-flex h-13 items-center justify-center rounded-lg border border-white/35 bg-white/10 px-6 text-sm font-bold text-white backdrop-blur transition hover:bg-white/20">Explore Products</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-slate-300"><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-amber-400"/>No inventory bias</span><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-amber-400"/>Confidential matching</span><span className="flex items-center gap-2"><CheckCircle2 size={15} className="text-amber-400"/>Transparent process</span></div></div></div></section>

    <section className="relative z-10 -mt-8"><div className="container-site grid overflow-hidden rounded-xl border border-slate-200 bg-white shadow-soft sm:grid-cols-2 lg:grid-cols-5">{trust.map(([Icon,label],i) => <div key={label} className={`flex min-h-28 items-center gap-3 px-5 py-6 ${i ? "border-t border-slate-100 sm:border-l sm:border-t-0" : ""}`}><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-700"><Icon size={20}/></span><span className="text-sm font-bold leading-5 text-slate-800">{label}</span></div>)}</div></section>

    <section className="section-pad"><div className="container-site"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="What we source" title="Products for industry, infrastructure and trade" description="Browse our sourcing capabilities, select products across multiple categories and send one coordinated requirement."/><Link href="/products" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-blue-700">Explore all products <ArrowRight size={17}/></Link></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{productCatalog.slice(0,8).map((c, i) => <article key={c.slug} className="group relative min-h-80 overflow-hidden rounded-xl bg-[#071a33]"><Image src={c.image} alt={c.name} fill className={`object-cover transition duration-500 group-hover:scale-105 ${i % 3 === 0 ? "object-left" : "object-center"}`} /><div className="absolute inset-0 image-shade"/><div className="absolute inset-x-0 bottom-0 p-6 text-white"><h3 className="font-display text-xl font-extrabold">{c.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-300">{c.description}</p><Link href={`/products#${c.slug}`} className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-amber-400">Explore category <ArrowRight size={15}/></Link></div></article>)}</div></div></section>

    <section className="section-pad bg-slate-50"><div className="container-site"><SectionHeading eyebrow="A clear process" title="How TradeBridge works" description="One coordinated workflow from initial requirement to a deal both sides can execute with confidence." align="center"/><div className="relative mt-14 grid gap-5 md:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-8 hidden h-px bg-blue-200 md:block"/>{[[ClipboardCheck,"Submit a requirement","Tell us the product, quantity, destination and commercial priorities."],[SearchCheck,"We identify suppliers","Our team searches the most suitable verified sourcing channels."],[MessageSquareText,"Compare matching offers","Receive structured options with specifications and commercial terms."],[Ship,"Coordinate deal & shipment","We support communication, documents and shipment handover."]].map(([Icon,title,text],i) => <div key={title as string} className="relative rounded-xl border border-slate-200 bg-white p-6"><div className="relative z-10 grid size-16 place-items-center rounded-full border-4 border-slate-50 bg-blue-700 text-white"><Icon size={25}/></div><span className="mt-6 block text-xs font-extrabold uppercase tracking-[.18em] text-blue-600">Step 0{i+1}</span><h3 className="mt-2 text-lg font-extrabold text-[#071a33]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text as string}</p></div>)}</div></div></section>

    <section className="section-pad"><div className="container-site"><SectionHeading eyebrow="Live deal flow" title="Featured sourcing opportunities" description="Representative products currently being sourced or offered through our network."/><div className="mt-10 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#071a33] text-xs uppercase tracking-wider text-slate-300"><tr>{["Product","Origin","Destination","Minimum quantity","Status",""] .map(x=><th key={x} className="px-5 py-4 font-bold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{opportunities.map(([product,origin,destination,qty,status]) => <tr key={product} className="transition hover:bg-slate-50"><td className="px-5 py-5 font-bold text-[#071a33]">{product}</td><td className="px-5 py-5">{origin}</td><td className="px-5 py-5">{destination}</td><td className="px-5 py-5">{qty}</td><td className="px-5 py-5"><Badge className={status === "Limited" ? "bg-amber-50 text-amber-700" : ""}>{status}</Badge></td><td className="px-5 py-5"><Link href="/contact?type=opportunity" className="font-bold text-blue-700">Request Details</Link></td></tr>)}</tbody></table></div></div></section>

    <section className="section-pad overflow-hidden bg-[#071a33] text-white"><div className="container-site grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[460px] overflow-hidden rounded-2xl"><Image src="/forklift-warehouse.jpg" alt="Warehouse equipment sourcing" fill className="object-cover"/><div className="absolute bottom-5 left-5 right-5 rounded-xl border border-white/15 bg-[#071a33]/90 p-5 backdrop-blur"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-lg bg-amber-400 text-[#071a33]"><Handshake/></div><div><strong className="block font-display text-lg">Aligned with your deal</strong><span className="text-sm text-slate-300">We earn when a transaction is completed.</span></div></div></div></div><div><span className="eyebrow !text-blue-300">Why choose us</span><h2 className="mt-4 font-display text-3xl font-extrabold md:text-5xl">Trade connections built on evidence, not guesswork.</h2><p className="mt-5 text-base leading-7 text-slate-300">We stay independent of inventory, so the sourcing process begins with your actual requirement—not a warehouse we need to clear.</p><div className="mt-8 grid gap-x-7 gap-y-4 sm:grid-cols-2">{why.map(x => <div key={x} className="flex items-start gap-3 text-sm font-semibold"><CheckCircle2 className="mt-0.5 shrink-0 text-amber-400" size={18}/>{x}</div>)}</div><Link href="/about" className="mt-9 inline-flex h-11 items-center gap-2 rounded-lg bg-white px-5 text-sm font-bold text-[#071a33]">Learn about our approach <ArrowRight size={16}/></Link></div></div></section>

    <section className="section-pad"><div className="container-site"><div className="rounded-2xl bg-blue-700 p-8 text-white md:p-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><ClipboardList size={36} className="text-blue-200"/><h2 className="mt-5 text-3xl font-extrabold md:text-4xl">Tell Us What You Need</h2><p className="mt-4 max-w-xl leading-7 text-blue-100">Select products from our categories and send one combined sourcing, discussion, or buying request.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/products" className="inline-flex h-12 items-center justify-center rounded-lg bg-amber-400 px-6 text-sm font-extrabold text-[#071a33]">Explore Products</Link><Link href="/request" className="inline-flex h-12 items-center justify-center rounded-lg border border-white/30 px-6 text-sm font-bold text-white">Submit a Requirement</Link></div></div><div className="grid gap-3 sm:grid-cols-2">{[[ListChecks,"Select products","Browse professional category sections."],[ClipboardList,"Build your Interest List","Combine products from different industries."],[PackageSearch,"Add commercial details","Enter quantities, condition and specifications."],[Send,"Send one request","Our team contacts you to discuss the opportunity."]].map(([Icon,title,text])=><div key={title as string} className="rounded-xl border border-white/15 bg-white/10 p-5"><Icon size={21} className="text-amber-300"/><strong className="mt-3 block text-sm">{title as string}</strong><span className="mt-1 block text-xs leading-5 text-blue-100">{text as string}</span></div>)}</div></div></div></div></section>

    <section className="section-pad border-t border-slate-100 bg-slate-50"><div className="container-site"><div className="flex items-end justify-between gap-6"><SectionHeading eyebrow="Market intelligence" title="Insights for better sourcing decisions"/><Link href="/market-insights" className="hidden items-center gap-2 text-sm font-bold text-blue-700 md:inline-flex">All insights <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{insightArticles.slice(0,3).map(a => <article key={a.slug} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative h-52"><Image src={a.image} alt="" fill className="object-cover"/></div><div className="p-6"><Badge>{a.category}</Badge><h3 className="mt-4 text-xl font-extrabold leading-snug text-[#071a33]"><Link href={`/market-insights/${a.slug}`}>{a.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate-600">{a.summary}</p><Link href={`/market-insights/${a.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700">Read More <ArrowRight size={15}/></Link></div></article>)}</div></div></section>
  </>;
}
