import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { articles } from "@/lib/site-data";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const a=articles.find(x=>x.slug===slug);return a?{title:a.title,description:a.excerpt}:{title:"Article not found"}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const a=articles.find(x=>x.slug===slug);if(!a)notFound();const schema={"@context":"https://schema.org","@type":"Article",headline:a.title,datePublished:a.date,image:`${process.env.NEXT_PUBLIC_SITE_URL||"https://tradebridge-global.example.com"}${a.image}`,publisher:{"@type":"Organization",name:"TradeBridge Global"}};return <article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="bg-[#071a33] py-16 text-white"><div className="container-site max-w-4xl"><Link href="/market-insights" className="inline-flex items-center gap-2 text-sm font-bold text-blue-200"><ArrowLeft size={16}/>Market Insights</Link><div className="mt-8 flex items-center gap-4"><Badge>{a.category}</Badge><span className="text-sm text-slate-400">{formatDate(a.date)}</span></div><h1 className="mt-5 text-4xl font-extrabold leading-tight md:text-5xl">{a.title}</h1><p className="mt-5 text-lg leading-8 text-slate-300">{a.excerpt}</p></div></header><div className="container-site max-w-4xl py-12"><div className="relative aspect-[16/8] overflow-hidden rounded-2xl"><Image src={a.image} alt="" fill priority className="object-cover"/></div><div className="mx-auto mt-10 max-w-3xl space-y-6 text-base leading-8 text-slate-700"><p>International sourcing decisions improve when buyers compare more than a headline price. Equipment condition, export readiness, documentation, packaging and shipment planning can materially change the final landed result.</p><h2 className="text-2xl font-extrabold text-[#071a33]">What buyers should evaluate</h2><p>Start with a clear specification and define acceptable alternatives. Request evidence appropriate to the product: operating videos and serial details for machinery, batch data for materials, or conformity documents for regulated goods.</p><p>Commercial comparisons should normalize currency, Incoterms, quantity, payment milestones and lead time. A lower unit price may not remain lower after preparation, inland logistics or document costs are included.</p><h2 className="text-2xl font-extrabold text-[#071a33]">A coordinated sourcing process</h2><p>TradeBridge Global helps buyers structure their requirement, identify suitable supply channels and coordinate verified introductions. Supplier and buyer contact information remains confidential until an approved match is ready to proceed.</p></div></div></article>}
