"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { createClient,isSupabaseConfigured } from "@/lib/supabase/client";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
const formSchema=z.object({email:z.string().email(),password:z.string().min(8),name:z.string().trim().optional(),company:z.string().trim().optional(),role:z.literal("buyer")});type Form=z.infer<typeof formSchema>;
export function AuthForm(){const[mode,setMode]=useState<"login"|"register">("login");const router=useRouter();const search=useSearchParams();const{register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<Form>({resolver:zodResolver(formSchema),defaultValues:{role:"buyer",name:"",company:""}});async function submit(v:Form){if(mode==="register"&&((v.name?.length||0)<2||(v.company?.length||0)<2)){toast.error("Enter your full name and company name.");return}const sb=createClient();if(!sb){await new Promise(r=>setTimeout(r,500));toast.success("Demo access enabled. Add Supabase credentials for real accounts.");router.push("/buyer-dashboard");return}if(mode==="login"){const{data,error}=await sb.auth.signInWithPassword({email:v.email,password:v.password});if(error){toast.error(error.message);return}const{data:p}=await sb.from("profiles").select("role").eq("id",data.user.id).single();router.push(search.get("next")||(p?.role==="admin"?"/admin":p?.role==="supplier"?"/supplier-dashboard":"/buyer-dashboard"))}else{const{error}=await sb.auth.signUp({email:v.email,password:v.password,options:{data:{full_name:v.name!,company_name:v.company!,role:"buyer"}}});if(error){toast.error(error.message);return}toast.success("Buyer account created. Check your email to confirm access.");setMode("login");reset()}}
return <><div className="flex rounded-lg bg-slate-100 p-1"><button onClick={()=>setMode("login")} className={`h-10 flex-1 rounded-md text-sm font-bold ${mode==="login"?"bg-white text-blue-700 shadow":"text-slate-500"}`}>Login</button><button onClick={()=>setMode("register")} className={`h-10 flex-1 rounded-md text-sm font-bold ${mode==="register"?"bg-white text-blue-700 shadow":"text-slate-500"}`}>Buyer account</button></div><form onSubmit={handleSubmit(submit)} className="mt-6 grid gap-4"><input type="hidden" value="buyer" {...register("role")}/>{mode==="register"&&<><Field label="Full name" error={errors.name?.message}><Input {...register("name")}/></Field><Field label="Company name" error={errors.company?.message}><Input {...register("company")}/></Field></>}<Field label="Email" error={errors.email?.message}><Input type="email" {...register("email")}/></Field><Field label="Password" error={errors.password?.message}><Input type="password" {...register("password")}/></Field><Button type="submit" size="lg" disabled={isSubmitting} className="mt-2 w-full">{isSubmitting?"Please wait…":mode==="login"?"Login":"Create buyer account"}</Button></form>{!isSupabaseConfigured()&&<p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">Demo mode is active. Any valid email and 8-character password opens the sample dashboard.</p>}</>}
