import type { WebsiteTemplate } from "./types";

// This static source mirrors the future Supabase row shape so the repository can
// be swapped without changing catalog or detail-page components.
export const templateCatalogData = [
  {
    id: "tpl_studio_launch",
    name: "Studio Launch",
    slug: "studio-launch",
    industry: "Agency",
    style: "Expressive",
    short_description: "A confident agency website for presenting expertise, selected work and a clear project enquiry path.",
    thumbnail: "/template-previews/studio-launch",
    screenshots: ["/template-previews/studio-launch?view=home", "/template-previews/studio-launch?view=inner"],
    demo_url: "/templates/studio-launch/demo",
    pages: ["Home", "Work", "Services", "About", "Contact"],
    features: ["Project-led homepage", "Portfolio grid", "Service overview", "Enquiry call to action"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-20T09:00:00.000Z",
  },
  {
    id: "tpl_local_pro",
    name: "Local Pro",
    slug: "local-pro",
    industry: "Local Business",
    style: "Clean",
    short_description: "A clear service website designed to turn local searches into qualified enquiries.",
    thumbnail: "/template-previews/local-pro",
    screenshots: ["/template-previews/local-pro?view=home", "/template-previews/local-pro?view=inner"],
    demo_url: "/templates/local-pro/demo",
    pages: ["Home", "Services", "Service Detail", "About", "Contact"],
    features: ["Service highlights", "Local trust section", "Contact form", "Mobile-first calls to action"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "tpl_ironline_build",
    name: "Ironline Build",
    slug: "ironline-build",
    industry: "Construction",
    style: "Bold",
    short_description: "A direct construction website for showcasing capabilities, completed work and quote-ready services.",
    thumbnail: "/template-previews/ironline-build",
    screenshots: ["/template-previews/ironline-build?view=home", "/template-previews/ironline-build?view=inner"],
    demo_url: "/templates/ironline-build/demo",
    pages: ["Home", "Services", "Projects", "About", "Contact"],
    features: ["Capability overview", "Project gallery", "Service detail layouts", "Quote enquiry flow"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-15T09:00:00.000Z",
  },
  {
    id: "tpl_consult_flow",
    name: "Consult Flow",
    slug: "consult-flow",
    industry: "Consulting",
    style: "Editorial",
    short_description: "An authority-led website for consultants who need to explain value and capture leads.",
    thumbnail: "/template-previews/consult-flow",
    screenshots: ["/template-previews/consult-flow?view=home", "/template-previews/consult-flow?view=inner"],
    demo_url: "/templates/consult-flow/demo",
    pages: ["Home", "Expertise", "Insights", "About", "Contact"],
    features: ["Expertise pages", "Insight previews", "Consultation call to action", "Lead form"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-12T09:00:00.000Z",
  },
  {
    id: "tpl_clearnest_cleaning",
    name: "ClearNest Cleaning",
    slug: "clearnest-cleaning",
    industry: "Cleaning",
    style: "Clean",
    short_description: "A fresh service website that makes cleaning packages, coverage areas and quote requests easy to understand.",
    thumbnail: "/template-previews/clearnest-cleaning",
    screenshots: ["/template-previews/clearnest-cleaning?view=home", "/template-previews/clearnest-cleaning?view=inner"],
    demo_url: "/templates/clearnest-cleaning/demo",
    pages: ["Home", "Services", "Service Areas", "About", "Contact"],
    features: ["Service package cards", "Coverage area section", "Before-and-after layout", "Quote request flow"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-09T09:00:00.000Z",
  },
  {
    id: "tpl_keyframe_property",
    name: "Keyframe Property",
    slug: "keyframe-property",
    industry: "Real Estate",
    style: "Premium",
    short_description: "A polished property showcase for independent agencies and specialist developments.",
    thumbnail: "/template-previews/keyframe-property",
    screenshots: ["/template-previews/keyframe-property?view=home", "/template-previews/keyframe-property?view=inner"],
    demo_url: "/templates/keyframe-property/demo",
    pages: ["Home", "Properties", "Property Detail", "Services", "About", "Contact"],
    features: ["Property cards", "Listing detail layout", "Agent enquiry flow", "Location highlights"],
    starting_price: 899,
    mobile_responsive: true,
    status: "available",
    featured: true,
    created_at: "2026-08-05T09:00:00.000Z",
  },
  {
    id: "tpl_table_tide",
    name: "Table & Tide",
    slug: "table-and-tide",
    industry: "Restaurant",
    style: "Editorial",
    short_description: "A warm restaurant concept built around menu discovery and reservation intent.",
    thumbnail: "/template-previews/table-and-tide",
    screenshots: ["/template-previews/table-and-tide?view=home", "/template-previews/table-and-tide?view=inner"],
    demo_url: "/templates/table-and-tide/demo",
    pages: ["Home", "Menu", "Story", "Reservations"],
    features: ["Menu presentation", "Opening hours", "Location section", "Reservation call to action"],
    starting_price: 399,
    mobile_responsive: true,
    status: "available",
    featured: false,
    created_at: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "tpl_brightline_dental",
    name: "Brightline Dental",
    slug: "brightline-dental",
    industry: "Dental",
    style: "Calm",
    short_description: "A calm dental practice concept planned around treatments, patient information and appointment enquiries.",
    thumbnail: "/template-previews/brightline-dental",
    screenshots: [],
    demo_url: null,
    pages: ["Home", "Treatments", "Dentists", "Patient Info", "About", "Contact"],
    features: ["Treatment directory", "Dentist profiles", "Patient information", "Appointment call to action"],
    starting_price: null,
    mobile_responsive: true,
    status: "coming-soon",
    featured: false,
    created_at: "2026-07-28T09:00:00.000Z",
  },
  {
    id: "tpl_groundwork_pro",
    name: "Groundwork Pro",
    slug: "groundwork-pro",
    industry: "Construction",
    style: "Clean",
    short_description: "A structured contractor concept planned for services, accreditations, project coverage and enquiries.",
    thumbnail: "/template-previews/groundwork-pro",
    screenshots: [],
    demo_url: null,
    pages: ["Home", "Services", "Projects", "Safety", "About", "Contact"],
    features: ["Service area overview", "Project case-study layout", "Safety and compliance section", "Enquiry form"],
    starting_price: null,
    mobile_responsive: true,
    status: "coming-soon",
    featured: false,
    created_at: "2026-07-24T09:00:00.000Z",
  },
  {
    id: "tpl_saffron_house",
    name: "Saffron House",
    slug: "saffron-house",
    industry: "Restaurant",
    style: "Warm",
    short_description: "A welcoming restaurant concept planned around signature dishes, atmosphere and reservation intent.",
    thumbnail: "/template-previews/saffron-house",
    screenshots: [],
    demo_url: null,
    pages: ["Home", "Menu", "Gallery", "Our Story", "Reservations"],
    features: ["Signature menu sections", "Dining gallery", "Opening hours", "Reservation call to action"],
    starting_price: null,
    mobile_responsive: true,
    status: "coming-soon",
    featured: false,
    created_at: "2026-07-20T09:00:00.000Z",
  },
] as const satisfies readonly WebsiteTemplate[];
