"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";
import { CheckCircle2, FileUp } from "lucide-react";
import { categories } from "@/lib/site-data";
import { createClient } from "@/lib/supabase/client";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Field } from "@/components/ui/field";
import { Button } from "@/components/ui/button";
const schema=z.object({companyName:z.string().trim().min(2).max(150),contactPerson:z.string().trim().min(2).max(80),email:z.string().email(),whatsapp:z.string().trim().min(7).max(30),country:z.string().trim().min(2).max(80),website:z.union([z.literal(""),z.string().url("Enter a complete URL")]),productCategories:z.array(z.string()).min(1,"Select at least one category"),mainProducts:z.string().trim().min(5).max(1000),companyType:z.enum(["Factory","Trader","Factory and trader"]),yearsInBusiness:z.number().int().min(0).max(200),exportMarkets:z.string().trim().min(2).max(500),certifications:z.string().max(500),moq:z.string().trim().min(1).max(100),paymentTerms:z.string().trim().min(2).max(300),description:z.string().trim().min(40,"Please provide at least 40 characters").max(2000)});
type Values=z.infer<typeof schema>; const fileTypes=["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","image/jpeg","image/png"];
export function SupplierForm(){const[profile,setProfile]=useState<File|null>(null);const[certs,setCerts]=useState<File|null>(null);const[done,setDone]=useState(false);const{register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{productCategories:[]}});
function validateFile(f:File|null){return !f||fileTypes.includes(f.type)&&f.size<=10*1024*1024}function pick(setter:(f:File|null)=>void,e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;if(!validateFile(f)){toast.error("Use PDF, DOCX, JPG or PNG up to 10 MB.");e.target.value="";return}setter(f)}
async function submit(v:Values){const supabase=createClient();let companyProfileUrl:string|undefined,certificatesUrl:string|undefined;if(supabase){for(const [file,key] of [[profile,"profile"],[certs,"certificates"]] as const){if(file){const path=`suppliers/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const res=await supabase.storage.from("trade-documents").upload(path,file,{contentType:file.type});if(res.error)throw new Error(res.error.message);if(key==="profile")companyProfileUrl=path;else certificatesUrl=path}}const{data:{user}}=await supabase.auth.getUser();const{data:supplier,error}=await supabase.from("suppliers").insert({user_id:user?.id||null,company_name:v.companyName,contact_person:v.contactPerson,contact_email:v.email,contact_phone:v.whatsapp,country:v.country,website:v.website||null,company_type:v.companyType,description:v.description,years_in_business:v.yearsInBusiness,export_markets:v.exportMarkets,certifications:v.certifications,payment_terms:v.paymentTerms,main_products:v.mainProducts,minimum_order_quantity:v.moq,company_profile_url:companyProfileUrl,certificates_url:certificatesUrl,verified:false,approval_status:"pending"}).select("id").single();if(error)throw new Error(error.message);const{data:cats}=await supabase.from("categories").select("id,name").in("name",v.productCategories);if(cats?.length)await supabase.from("supplier_categories").insert(cats.map(c=>({supplier_id:supplier.id,category_id:c.id})));await supabase.from("admin_notifications").insert({event_type:"supplier_registered",entity_type:"supplier",entity_id:supplier.id,message:`New supplier: ${v.companyName}`})}else await new Promise(r=>setTimeout(r,700));setDone(true);reset();toast.success("Supplier profile submitted for review.")}
if(done)return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center"><CheckCircle2 size={44} className="mx-auto text-emerald-600"/><h2 className="mt-4 text-2xl font-extrabold text-emerald-950">Registration received</h2><p className="mt-3 text-sm leading-6 text-emerald-800">Your profile is pending review. We may contact you for verification before making it visible or sharing buyer requirements.</p></div>;
return <form onSubmit={handleSubmit(submit)} className="space-y-8"><div className="grid gap-5 md:grid-cols-2"><Field label="Company name" error={errors.companyName?.message}><Input {...register("companyName")}/></Field><Field label="Contact person" error={errors.contactPerson?.message}><Input {...register("contactPerson")}/></Field><Field label="Business email" error={errors.email?.message}><Input type="email" {...register("email")}/></Field><Field label="WhatsApp" error={errors.whatsapp?.message}><Input {...register("whatsapp")}/></Field><Field label="Country" error={errors.country?.message}><Input {...register("country")}/></Field><Field label="Website" error={errors.website?.message}><Input placeholder="https://" {...register("website")}/></Field><Field label="Factory or trader" error={errors.companyType?.message}><Select {...register("companyType")}><option value="">Select type</option><option>Factory</option><option>Trader</option><option>Factory and trader</option></Select></Field><Field label="Years in business" error={errors.yearsInBusiness?.message}><Input type="number" min="0" {...register("yearsInBusiness",{valueAsNumber:true})}/></Field></div><Field label="Product categories" error={errors.productCategories?.message}><div className="grid gap-2 rounded-xl border border-slate-200 p-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=><label key={c.slug} className="flex items-center gap-2.5 text-sm text-slate-700"><input type="checkbox" value={c.name} {...register("productCategories")} className="size-4 accent-blue-700"/>{c.name}</label>)}</div></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Main products" error={errors.mainProducts?.message}><Textarea {...register("mainProducts")}/></Field><Field label="Export markets" error={errors.exportMarkets?.message}><Textarea placeholder="Countries or regions" {...register("exportMarkets")}/></Field><Field label="Certifications" error={errors.certifications?.message}><Input placeholder="ISO 9001, CE, JIS…" {...register("certifications")}/></Field><Field label="Typical MOQ" error={errors.moq?.message}><Input {...register("moq")}/></Field><Field label="Payment terms" error={errors.paymentTerms?.message} className="md:col-span-2"><Input placeholder="e.g. 30% advance, 70% before shipment" {...register("paymentTerms")}/></Field><Field label="Short company description" error={errors.description?.message} className="md:col-span-2"><Textarea rows={5} {...register("description")}/></Field></div><div className="grid gap-4 md:grid-cols-2"><Upload label="Upload company profile" file={profile} onChange={e=>pick(setProfile,e)}/><Upload label="Upload certificates" file={certs} onChange={e=>pick(setCerts,e)}/></div><div className="flex justify-end border-t border-slate-200 pt-6"><Button type="submit" size="lg" disabled={isSubmitting}>{isSubmitting?"Submitting…":"Register company"}</Button></div></form>}
function Upload({label,file,onChange}:{label:string;file:File|null;onChange:(e:React.ChangeEvent<HTMLInputElement>)=>void}){return <label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5"><FileUp className="text-blue-700"/><span><strong className="block text-sm">{label}</strong><span className="text-xs text-slate-500">PDF, DOCX, JPG or PNG · 10 MB max</span>{file&&<span className="block text-xs font-semibold text-blue-700">{file.name}</span>}</span><input className="sr-only" type="file" accept=".pdf,.docx,.jpg,.jpeg,.png" onChange={onChange}/></label>}
